### ISSUE TITLE
Sample?

### ISSUE THREAD

**Issue by sgentile** [stoodder/falconjs#1]
Looks good - would like to see a sample showing how it's used, etc...

Thanks!

**Comment by stoodder** [comment]
Sure thing, here's a basic example: http://jsfiddle.net/stoodder/cuTcr/light/

Are you looking for an example of this used in a fullscale application?

**Comment by bitfool** [comment]
Go ahead and close this ticket, your documentation is great for the escalating ToDo example.  Dunno what things looked like two months ago, but for 0.8.0 this is a nonissue.
