### ISSUE TITLE
Coffeescript extends vs. .extend()

### ISSUE THREAD

**Issue by stefandraht** [stoodder/falconjs#18]
Is there a way to use CoffeeScript's inheritance (extends) rather than the Falcon.Object extend() method?

For example:
class Todo extends Falcon.Model

rather than

Todo = Falcon.Model.extend

**Comment by stoodder** [comment]
@stefandraht If you're using coffee in your app currently, then you'll already be able to use coffee script's inheritance!  Are you currently using coffee? If so, what issue are you running in to?

**Comment by stefandraht** [comment]
Fantastic!
It turns out I was using the Coffeescript 'constructor' instead of 'initialize' for some of my object set up which was causing issues with when observables were being created and populated. It's all working now and looking nice and clean in Coffeescript. Thanks!

**Comment by stoodder** [comment]
No problem! Thanks for using the library, let me know if you have any other feedback or questions.
